### ISSUE TITLE
Can't get the portals to work with the signs....

### ISSUE THREAD

**Issue by Dnaleor77** [Multiverse/Multiverse-SignPortals#75] opened 2021-01-07 09:31 UTC
Information:
server version: Paper-1.16.4-393
Multiverse version output: https://j.mp/3bhzbU8
nothing in server log about mv-signportals...

So I installed the signportals last week and went on trying it out, but I can't seem to get them to work... The issue could be the same as in:
https://github.com/Multiverse/Multiverse-SignPortals/issues/53
I am not sure if it is a bug or me just being silly again...

Steps I take to create the portal for destination "world"
1. Creat a nether portal as usual
2. put a sign on the portal with: first line blank, second line "[MV]" third line destination "world"
3. check the colors on the sign (green [MV] for succesfull configuration)
4. step into portal - noting happens...
5. check sign again for colors (blue [MV] for succesfull activation)

Now the thing is, when finished with the sign, right clicking on it actually takes me to the destination world, but after entering the portal, rightclicking the sign stops working for me to.

**Comment by zax71** [comment] 2024-04-24 17:45
Yep, I think you are correct. This is a duplicate of #53

**Comment by zax71** [comment] 2024-04-24 17:46
Duplicate of #53

**Closed by zax71** 2024-04-24 17:46 UTC
Labels: Assistance
